using UnityEngine;
using UnityEngine.Rendering;
using System.Collections.Generic;

namespace CensorEffect.Runtime
{
    [ExecuteInEditMode]
    [AddComponentMenu("Effects/Censor Effect")]
    [RequireComponent(typeof(Camera))]
    public class CensorEffect : MonoBehaviour
    {
        #region Public Settings

        [Header("Censor Settings")]
        [Tooltip("Layers to be censored.")]
        public LayerMask CensorLayer = 0;

        [Tooltip("Use the depth buffer to hide censored objects behind other objects.")]
        public bool EnableOcclusion = true;

        [Tooltip("The number of pixel blocks to draw across the screen's height. Smaller numbers mean larger blocks.")]
        [Range(1, 512)]
        public float PixelBlockCount = 100f;

        [Tooltip("How much to expand the censored area, in pixels.")]
        [Range(0, 50)]
        public int CensorAreaExpansionPixels = 5;

        [Header("Appearance")]
        [Tooltip("Enable smooth edges on censored areas.")]
        public bool EnableAntiAliasing = true;

        #endregion

        #region Private Fields

        [Header("Shader References")]
        [SerializeField] private Shader _censorMaskShader;
        [SerializeField] private Shader _censorEffectShader;
        [SerializeField] private Shader _dilationShader;

        private Material _censorMaskMaterial;
        private Material _censorEffectMaterial;
        private Material _dilationMaterial;

        private Camera _mainCamera;

        // Command Buffer for rendering the censor mask
        private CommandBuffer _commandBuffer;
        private int _censorMaskID;

        // List of renderers to be censored
        private List<Renderer> _renderersToCensor = new List<Renderer>();

        private static readonly int PixelSizeID = Shader.PropertyToID("_PixelSize");
        private static readonly int CensorMaskGlobalID = Shader.PropertyToID("_CensorMask");
        private static readonly int AntiAliasingID = Shader.PropertyToID("_AntiAliasing");
        private static readonly int DilationSizeID = Shader.PropertyToID("_DilationSize");

        #endregion

        #region Unity Methods

        private void OnEnable()
        {
            _mainCamera = GetComponent<Camera>();
            _mainCamera.depthTextureMode |= DepthTextureMode.Depth;

            _censorMaskID = Shader.PropertyToID("_CensorMaskRT");

            FindAndCacheRenderers();
            CreateResources();
            SetupCommandBuffer();
        }

        private void OnDisable()
        {
            CleanupCommandBuffer();
            CleanupResources();
        }

        private void OnRenderImage(RenderTexture source, RenderTexture destination)
        {
            if (!AreResourcesCreated())
            {
                Graphics.Blit(source, destination);
                return;
            }

            UpdateMaterialProperties();

            // The _CensorMask texture is generated by the CommandBuffer.
            // We just need to process it (dilate) and use it for the final composite.
            if (CensorAreaExpansionPixels > 0)
            {
                var maskDescriptor = new RenderTextureDescriptor(source.width, source.height, RenderTextureFormat.R8, 0)
                {
                    msaaSamples = 1, // Dilation doesn't need MSAA
                    sRGB = false
                };
                var dilatedMask = RenderTexture.GetTemporary(maskDescriptor);
                ApplyDilation(new RenderTargetIdentifier(_censorMaskID), dilatedMask);

                // Use the dilated mask for the effect and release it.
                _censorEffectMaterial.SetTexture(CensorMaskGlobalID, dilatedMask);
                Graphics.Blit(source, destination, _censorEffectMaterial);
                RenderTexture.ReleaseTemporary(dilatedMask);
            }
            else
            {
                // If no dilation, the mask is already available as a global texture
                // set by the command buffer. We can just run the effect.
                Graphics.Blit(source, destination, _censorEffectMaterial);
            }
        }

        #endregion

        #region Core Logic

        private void FindAndCacheRenderers()
        {
            _renderersToCensor.Clear();
            var allRenderers = FindObjectsOfType<Renderer>();
            foreach (var renderer in allRenderers)
            {
                if (renderer.isVisible && (CensorLayer & (1 << renderer.gameObject.layer)) != 0)
                {
                    _renderersToCensor.Add(renderer);
                }
            }
        }

        private void SetupCommandBuffer()
        {
            if (_commandBuffer != null)
            {
                CleanupCommandBuffer();
            }

            _commandBuffer = new CommandBuffer { name = "Censor Effect Mask" };

            // Get a temporary render texture to act as the mask.
            // The format is R8 with a 16-bit depth buffer for occlusion testing.
            _commandBuffer.GetTemporaryRT(_censorMaskID, -1, -1, 16, FilterMode.Bilinear, RenderTextureFormat.R8);

            // Render the mask
            _commandBuffer.SetRenderTarget(_censorMaskID);
            _commandBuffer.ClearRenderTarget(true, true, Color.clear);
            foreach (var renderer in _renderersToCensor)
            {
                if (renderer != null)
                {
                    _commandBuffer.DrawRenderer(renderer, _censorMaskMaterial);
                }
            }

            // Make the mask available globally for the final composition shader.
            _commandBuffer.SetGlobalTexture(CensorMaskGlobalID, _censorMaskID);

            // Release the temporary render texture after it has been used.
            _commandBuffer.ReleaseTemporaryRT(_censorMaskID);

            _mainCamera.AddCommandBuffer(CameraEvent.BeforeImageEffects, _commandBuffer);
        }

        private void ApplyDilation(RenderTargetIdentifier source, RenderTexture destination)
        {
            var tempDilateTex = RenderTexture.GetTemporary(destination.descriptor);
            _dilationMaterial.SetInt(DilationSizeID, CensorAreaExpansionPixels);

            Graphics.Blit(source, tempDilateTex, _dilationMaterial, 0); // Horizontal
            Graphics.Blit(tempDilateTex, destination, _dilationMaterial, 1); // Vertical

            RenderTexture.ReleaseTemporary(tempDilateTex);
        }

        private void UpdateMaterialProperties()
        {
            _censorEffectMaterial.SetFloat(PixelSizeID, PixelBlockCount);
            _censorEffectMaterial.SetFloat(AntiAliasingID, EnableAntiAliasing ? 1f : 0f);

            if (EnableOcclusion)
            {
                _censorMaskMaterial.EnableKeyword("_OCCLUSION_ON");
            }
            else
            {
                _censorMaskMaterial.DisableKeyword("_OCCLUSION_ON");
            }
        }

        #endregion

        #region Resource Management

        private void CreateResources()
        {
            _censorMaskMaterial = CreateMaterial(_censorMaskShader);
            _censorEffectMaterial = CreateMaterial(_censorEffectShader);
            _dilationMaterial = CreateMaterial(_dilationShader);
        }

        private bool AreResourcesCreated()
        {
            return _censorEffectMaterial != null && _censorMaskMaterial != null && _dilationMaterial != null;
        }

        private void CleanupResources()
        {
            if (_censorMaskMaterial != null) DestroyImmediate(_censorMaskMaterial);
            if (_censorEffectMaterial != null) DestroyImmediate(_censorEffectMaterial);
            if (_dilationMaterial != null) DestroyImmediate(_dilationMaterial);

            _censorMaskMaterial = null;
            _censorEffectMaterial = null;
            _dilationMaterial = null;
        }

        private void CleanupCommandBuffer()
        {
            if (_commandBuffer != null)
            {
                _mainCamera.RemoveCommandBuffer(CameraEvent.BeforeImageEffects, _commandBuffer);
                _commandBuffer.Release();
                _commandBuffer = null;
            }
        }

        private int GetMsaaSampleCount(RenderTexture source)
        {
            return source.antiAliasing > 1 ? source.antiAliasing : 1;
        }

        private Material CreateMaterial(Shader shader)
        {
            if (shader == null || !shader.isSupported) return null;
            return new Material(shader) { hideFlags = HideFlags.HideAndDontSave };
        }

        #endregion
    }
}
